name: "TEST [SELENIUM]"
#type: Workflow Trigger

on:
  push:
    # Already covered by "deploy.yml" workflow
    branches:
      - '!main'
      - '!master'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "[ref] e.g. branch, tag or commit to checkout [default: github_ref_name || github_head_ref ]"
        required: false
      skip_test:
        description: "[skip_test] skips tests when 'true'"
        type: string
        required: false

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: "Checkout"
        if: ${{ inputs.skip_test != 'true' }}
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          ref: ${{ steps.inputs.outputs.ref }}
      - name: "Setup Chrome"
        uses: browser-actions/setup-chrome@v1
      - name: "Setup Node"
        if: ${{ inputs.skip_test != 'true' }}
        uses: actions/setup-node@main
        with:
          node-version: "16"
          cache: npm
      - name: "Run Selenium tests with Browser Stack"

        run: |
          npm install 
          npm run suite
        env:
          #SELENIUM_EP2_USER: ${{secrets.SELENIUM_EP2_USER}}
          #SELENIUM_EP2_KEY: ${{secrets.SELENIUM_EP2_KEY}}
          #EP2_API_CLIENT_ID: ${{secrets.EP2_API_CLIENT_ID}}
          #EP2_API_CLIENT_SECRET: ${{secrets.EP2_API_CLIENT_SECRET}}
          BROWSERSTACK_USER: ${{secrets.BROWSERSTACK_USER}}
          BROWSERSTACK_KEY: ${{secrets.BROWSERSTACK_KEY}}